build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Rock Start - Developer"
    email: "rock@eazybank.com"
  onCallSupport:
    - "(999) 555-1234"
    - "(999) 523-1345"

