build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Tom Latham - Developer"
    email: "tom@eazybank.com"
  onCallSupport:
    - "(666) 555-1234"
    - "(666) 523-1345"
